### ISSUE TITLE
패키지별 린트 활성화

### ISSUE THREAD

**Issue by zprime0920** [titicacadev/triple-frontend#1755]
#1737 에서 끈 린트 검사를 패키지별로 활성화합니다.
네이밍 컨벤션이나 no-any 규칙을 수정하면서 Breaking Change가 발생하기 쉽습니다. 그래서 점진적으로 린트 오류를 수정하고 린트 규칙을 활성화하기로 결정했습니다.

## 참여하기

1. 아래의 목록에서 작업하실 패키지를 찾아 이름을 적어주세요.
2. `.eslintignore`나 `.stylelintignore`에서 해당 패키지를 찾아 줄을 지워주세요.
3. `npm run lint`로 오류를 찾으세요.
4. 모두 수정한 후 PR을 만들어주세요.
5. Breaking Change를 만들었다면 PR에서 꼭 알려주세요.

### 팁

- 네이밍 변경은 Breaking Change가 일어날 수 있습니다. src/index에서 노출하고 있는 identifier라면 이름이 바뀌는 것은 Breaking Change입니다. 당장 Breaking Change를 만들고 싶지 않다면 해당 라인에 린트 규칙을 비활성화하거나 `allowedNames`에 추가하세요.
- any 대신 쓸 타입이 아무리해도 어려운 경우가 있습니다. 이때는 그냥 린트 규칙을 비활성화하고 넘어가세요. 이미 릴리즈한 코드의 타입을 다시 짜 맞추기는 힘들 수 있습니다.

### ESLint

작업하실 패키지 옆에 이름을 적어주세요.

- [x] view-utilities #1758
- [x] fetcher #1766, #1767
- [x] router #1768
- [x] date-picker #1775
- [x] ad-banners #1786 #1787 
- [x] footer #1788 #1789
- [x] modals #1790 #1791
- [x] nearby-pois #1792
- [x] standard-action-handler #1794 
- [x] triple-document #1795 
- [x] review #1793 
- [x] react-contexts #1797 #1798
- [x] docs #1801
- [x] user-verification #1809
- [x] replies #1810
- [x] map #1841 
- [x] core-elements #1850
- [x] ui-flow #1857 
- [x] public-header #1898
- [x] poi-detail #1899
- [x] i18n #2006
- [x] intersection-observer #1973 
- [x] react-hooks #1979 
- [x] scrap-button #1974 
- [x] style-box #1977 
- [x] type-definitions #1978 
- [x] web-storage #1981
- [x] listing-filter #1982 
- [x] static-page-contents #1983 
- [x] ab-experiments #1987 
- [x] action-sheet #2003 
- [x] app-banner #1988 
- [x] app-installation-cta #1993
- [x] author #1997 
- [x] content-sharing #1996
- [x] hub-form #1995
- [x] image-carousel #1994
- [x] pricing #1992
- [x] recommended-contents #1991
- [x] search #1990
- [x] slider #1989
- [x] form #1986 
- [x] poi-list-elemnts #1984 

### Stylelint

- [x] date-picker #1775
- [x] docs #1801 
- [x] core-elements #1850
- [x] author #1997 
- [x] form #1986

**Comment by inbeom** [comment]
모두 클리어한 것 같네요! 요거 후련하게 닫겠습니다 :bow: 다들 너무 고생많으셨습니다!!
